services:
  easypipe-postgres:
    image: postgres:17.4
    container_name: easypipe-postgres
    environment:
      POSTGRES_USER: easypipe
      POSTGRES_PASSWORD: easypipe
      POSTGRES_DB: easypipe
    ports:
      - "5432:5432"
    volumes:
      - easypipe-data:/var/lib/postgresql/data
    networks:
      - easypipe-network

volumes:
  easypipe-data:

networks:
  easypipe-network:
